version: "3"


  services:
    zawoke.ts:
      container_name: zawoke
      hostname: zawoke
      restart: always
      image: zawoke
      build:
        context: .
      environment:
        - DOCKER_MODE=True
      volumes:
       - ./source:/app/source
