version: "3"


services:
  zawoke.ts:
    container_name: "zawoke.ts"
    hostname: "zawoke.ts"
    restart: "no"
    image: "zawoke.ts"
    build:
      context: .
    environment:
      - DOCKER_MODE=True
    volumes:
     - ./:/usr/local/zawoke/app
     - exclude:/usr/local/zawoke/app/node_modules

volumes:
  exclude:
