version: "3"


services:
  zawoke.ts:
    container_name: zawoke.ts
    hostname: zawoke.ts
    restart: always
    image: zawoke.ts
    build:
      context: .
    environment:
      - DOCKER_MODE=True
    volumes:
     - ./source:/app/source
